FROM node:10-alpine

WORKDIR /app

# Needed when running in AWS on c5/m5/t3, see
# https://github.com/npm/npm/issues/20861
RUN npm config set unsafe-perm true

RUN npm install -g ganache-cli@beta

EXPOSE 8545/tcp

CMD ganache-cli -m zippie -a 101 -v -h 0.0.0.0 --hardfork constantinople
